import React from 'react'
const data=[
    {
        "firstName": "John",
        "fatherName": "Michael Doe",
        "fatherBirthDate": "1960-04-15",
        "fatherOccupation": "Engineer",
        "motherName": "Jane Doe",
        "motherBirthDate": "1962-07-20",
        "motherOccupation": "Teacher",
        "address": "123 Main St, Apt 4B",
        "city": "New York",
        "zipCode": "10001",
        "state": "NY",
        "email": "john.doe@example.com",
        "phHome": "212-555-1234",
        "phonePersonal": "917-555-5678",
        "alternative": "917-555-9876",
        "birthDate": "1990-01-01",
        "age": "34",
        "gender": "Male",
        "maritalStatus": "Single",
        "aadhar": "1234-5678-9012",
        "pan": "ABCDE1234F",
        "uan": "101234567890",
        "esi": "1234567890",
        "bank": "Bank of America",
        "account": "1234567890",
        "ifsc": "BOFAUS3N",
        "spouse": "",
        "spouseAge": "",
        "spouseGender": "",
        "spouseBirthDate": "",
        "children1": "",
        "childrenGender1": "",
        "childrenDob1": "",
        "childrenAge1": "",
        "children2": "",
        "childrenGender2": "",
        "childrenDob2": "",
        "childrenAge2": "",
        "schoolName": "Central High School",
        "boardName": "CBSE",
        "schoolPass": "2005",
        "schoolGrade": "A",
        "interName": "St. Paul’s College",
        "interBoard": "CBSE",
        "interPass": "2007",
        "interGrade": "A",
        "graduationName": "New York University",
        "graduationBoard": "NYU",
        "graduationPass": "2011",
        "graduationGrade": "A",
        "pgBoard": "NYU",
        "pgPass": "2013",
        "pgName": "New York University",
        "pgGrade": "A",
        "certifications": [
            {"courseName": "Project Management", "issueAuthority": "PMI", "tenure": "6 months", "certificateDate": "2014-06-01"}
        ],
        "experience": [
            {"companyName": "Tech Solutions", "designation": "Software Engineer", "department": "IT", "tenure": "2015-2020"}
        ],
        "skillsByCategory": {
            "technical": ["JavaScript", "Python", "React"],
            "soft": ["Communication", "Leadership"]
        },
        "responsibilities": "Developing and maintaining web applications",
        "role": "Developer",
        "team": "Web Development",
        "supervisorName": "Alice Johnson",
        "supervisorInfo": "alice.johnson@example.com",
        "designation": "Senior Developer",
        "reportingTo": "CTO",
        "empId": "EMP12346",
        "yearsOfExperience": "9"
    },
    {
        "firstName": "Alice",
        "fatherName": "Robert Smith",
        "fatherBirthDate": "1965-08-10",
        "fatherOccupation": "Doctor",
        "motherName": "Emily Smith",
        "motherBirthDate": "1968-11-30",
        "motherOccupation": "Nurse",
        "address": "456 Elm St, Apt 5C",
        "city": "Los Angeles",
        "zipCode": "90001",
        "state": "CA",
        "email": "alice.smith@example.com",
        "phHome": "310-555-7890",
        "phonePersonal": "818-555-1234",
        "alternative": "818-555-5678",
        "birthDate": "1992-05-15",
        "age": "32",
        "gender": "Female",
        "maritalStatus": "Married",
        "aadhar": "2345-6789-0123",
        "pan": "FGHIJ2345K",
        "uan": "201234567890",
        "esi": "2345678901",
        "bank": "Wells Fargo",
        "account": "2345678901",
        "ifsc": "WFBIUS6S",
        "spouse": "Bob Johnson",
        "spouseAge": "34",
        "spouseGender": "Male",
        "spouseBirthDate": "1990-02-20",
        "children1": "Sophie Johnson",
        "childrenGender1": "Female",
        "childrenDob1": "2015-03-25",
        "childrenAge1": "9",
        "children2": "Liam Johnson",
        "childrenGender2": "Male",
        "childrenDob2": "2018-07-15",
        "childrenAge2": "5",
        "schoolName": "West High School",
        "boardName": "CBSE",
        "schoolPass": "2007",
        "schoolGrade": "A",
        "interName": "Greenwood College",
        "interBoard": "CBSE",
        "interPass": "2009",
        "interGrade": "A",
        "graduationName": "University of California",
        "graduationBoard": "UC",
        "graduationPass": "2013",
        "graduationGrade": "A",
        "pgBoard": "UC",
        "pgPass": "2015",
        "pgName": "University of California",
        "pgGrade": "A",
        "certifications": [
            {"courseName": "Data Science", "issueAuthority": "Coursera", "tenure": "8 months", "certificateDate": "2016-11-01"}
        ],
        "experience": [
            {"companyName": "Data Corp", "designation": "Data Analyst", "department": "Data Science", "tenure": "2016-2021"}
        ],
        "skillsByCategory": {
            "technical": ["R", "Python", "SQL"],
            "soft": ["Analytical Thinking", "Problem-Solving"]
        },
        "responsibilities": "Analyzing data and providing insights",
        "role": "Data Analyst",
        "team": "Data Science",
        "supervisorName": "John Doe",
        "supervisorInfo": "john.doe@datacorp.com",
        "designation": "Lead Data Analyst",
        "reportingTo": "Head of Data Science",
        "empId": "EMP67",
        "yearsOfExperience": "8"
    }
];
const Data = () => {
   
  return (
    <div>hello world</div>
  )
}

export default data;
